pipeline {
    agent any

    tools{
    	maven 'maven 3.6.1'
    }

    stages {
        stage("build") {
            steps {
                echo 'Compiling Maven app'
                dir(worker)
		sh 'mvn compile'
            }
        }
        stage("test") {
           steps {
               echo 'Testing Maven app'
               dir(worker)
               sh 'mvn clean test'
           }
        }

        stage("package") {
           steps {
               echo 'Packaging Maven app'
               dir(worker)
               sh 'mvn package'
           }
        }

    }
    post{
        always{
            echo 'Pipeline succesfully'
        }
    }
}

